spring.application.name=WeirdWebApi
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crawler}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:nicholasmckendall}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
